In [1]:
from pathlib import Path

path = Path("./filter2_dir")
# .name extracts just the file name string
files = [f.name for f in path.iterdir() if f.is_file()]

In [2]:
files[0]

'50598.wav'

In [3]:
len(files)

23768

In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("data_ok.csv")

In [6]:
df

           index                                                txt
0      40858.wav                       อ่านสนุก จนน่าจะพิมพ์รวมเล่ม
1      33290.wav                         วันอาทิตย์ไม่โอเคสำหรับฉัน
2      50598.wav        แต่เขาฝันว่าเขาเป็นอมตะ ฉันแย้งอย่างอ่อนแรง
3      37483.wav                              หรือผู้ผ่านการต้องขัง
4       7156.wav                               คุณทำแบบนั้นเพื่อใคร
...          ...                                                ...
39195  46777.wav           เมื่อมีหิมะ พวกเขาออกไปเล่นเลื่อนน้ำแข็ง
39196  48938.wav                  เหล็กถูกนำมาใช้ใหม่อย่างกว้างขวาง
39197   2338.wav  การอ่านครั้งแรกบ่งบอกถึงการไหลเข้าของสารเคมีเป...
39198   4998.wav                         คนภูเก็ตที่ทำงานนอกพื้นที่
39199   9151.wav  จากนั้นคนส่วนผสมให้เข้ากันจนเดือดกลายเป็นสีน้ำตาล

[39200 rows x 2 columns]

In [7]:
df = df[df['index'].isin(files)]

In [8]:
df["audio_filepath"]=["filter2_dir/"+i for i in df["index"]]

/tmp/ipykernel_5337/1784957712.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["audio_filepath"]=["filter2_dir/"+i for i in df["index"]]

In [9]:
df["text"]=df["txt"]

/tmp/ipykernel_5337/334303586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text"]=df["txt"]

In [10]:
df

,index,txt,audio_filepath,text
2,50598.wav,แต่เขาฝันว่าเขาเป็นอมตะ ฉันแย้งอย่างอ่อนแรง,filter2_dir/50598.wav,แต่เขาฝันว่าเขาเป็นอมตะ ฉันแย้งอย่างอ่อนแรง
5,5841.wav,ความมั่งคั่ง ความยากจนและความเหลื่อมล้ำ,filter2_dir/5841.wav,ความมั่งคั่ง ความยากจนและความเหลื่อมล้ำ
7,1959.wav,การพัฒนานวัตกรรมให้เข้มแข็ง,filter2_dir/1959.wav,การพัฒนานวัตกรรมให้เข้มแข็ง
12,27280.wav,มหาวิทยาลัยศิลปากร ผลิตจิตรกรชื่อดังจำนวนมาก,filter2_dir/27280.wav,มหาวิทยาลัยศิลปากร ผลิตจิตรกรชื่อดังจำนวนมาก
18,32902.wav,วงการเพลง หนัง เกมทำได้ วงการข่าวก็น่าจะทำได้ฮะ,filter2_dir/32902.wav,วงการเพลง หนัง เกมทำได้ วงการข่าวก็น่าจะทำได้ฮะ
...,...,...,...,...
39194,52180.wav,และสนับสนุนการขยายธุรกิจในสาขาที่ผู้ประกอบการไ...,filter2_dir/52180.wav,และสนับสนุนการขยายธุรกิจในสาขาที่ผู้ประกอบการไ...
39195,46777.wav,เมื่อมีหิมะ พวกเขาออกไปเล่นเลื่อนน้ำแข็ง,filter2_dir/46777.wav,เมื่อมีหิมะ พวกเขาออกไปเล่นเลื่อนน้ำแข็ง
39196,48938.wav,เหล็กถูกนำมาใช้ใหม่อย่างกว้างขวาง,filter2_dir/48938.wav,เหล็กถูกนำมาใช้ใหม่อย่างกว้างขวาง
39197,2338.wav,การอ่านครั้งแรกบ่งบอกถึงการไหลเข้าของสารเคมีเป...,filter2_dir/2338.wav,การอ่านครั้งแรกบ่งบอกถึงการไหลเข้าของสารเคมีเป...
39199,9151.wav,จากนั้นคนส่วนผสมให้เข้ากันจนเดือดกลายเป็นสีน้ำตาล,filter2_dir/9151.wav,จากนั้นคนส่วนผสมให้เข้ากันจนเดือดกลายเป็นสีน้ำตาล

In [11]:
del df["index"]
del df["txt"]

In [12]:
df.to_csv("data_use.csv",index=False)

In [13]:
from datasets import config

# Force the datasets library to ignore torchcodec and fallback to soundfile
config.TORCHCODEC_AVAILABLE = False
from datasets import load_dataset, Audio

# 1. Load the dataset from your CSV file
# Change 'train' to whatever split makes sense, or omit it to load as a DatasetDict
dataset = load_dataset("csv", data_files="data_use.csv", split="train")

# 2. (Optional but Recommended) Rename the column
# Most HF models expect the audio column to be named simply 'audio'
dataset = dataset.rename_column("audio_filepath", "audio")

Generating train split: 0 examples [00:00, ? examples/s]

In [14]:
dataset = dataset.cast_column("audio", Audio(decode=True))

In [15]:
dataset

Dataset({
    features: ['audio', 'text'],
    num_rows: 23768
})

In [16]:
dataset[0]

{'audio': {'path': 'filter2_dir/50598.wav',
  'array': array([0., 0., 0., ..., 0., 0., 0.], shape=(69360,)),
  'sampling_rate': 24000},
 'text': 'แต่เขาฝันว่าเขาเป็นอมตะ ฉันแย้งอย่างอ่อนแรง'}

In [1]:
dataset.push_to_hub("pythainlp/som_tts_dataset",)

NameError: name 'dataset' is not defined